###  지난 시간에 구현한 함수들을 다음과 같은 구조로 package를 만듦

        myLA
          |
          |....  __init__.py
          |
          |....  util.py (myprint함수, sgn함수, myLU함수)
          |....  swap.py (swapRows함수, swapCols함수)
          |....  gaussPivot.py (gaussPivot함수)
          |....  LUpivot.py (LUdecomp함수, LUsolve_pre함수, LUsolve함수, (matInv함수, matDet함수))



In [1]:
import numpy as np
from myLA.LUpivot import *
import sys

In [2]:
sys.path

['C:\\Users\\Kil-Chan Ha\\Documents\\Cal2020',
 'C:\\Users\\Kil-Chan Ha\\.conda\\envs\\Cal2020\\python37.zip',
 'C:\\Users\\Kil-Chan Ha\\.conda\\envs\\Cal2020\\DLLs',
 'C:\\Users\\Kil-Chan Ha\\.conda\\envs\\Cal2020\\lib',
 'C:\\Users\\Kil-Chan Ha\\.conda\\envs\\Cal2020',
 '',
 'C:\\Users\\Kil-Chan Ha\\.conda\\envs\\Cal2020\\lib\\site-packages',
 'C:\\Users\\Kil-Chan Ha\\.conda\\envs\\Cal2020\\lib\\site-packages\\win32',
 'C:\\Users\\Kil-Chan Ha\\.conda\\envs\\Cal2020\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Kil-Chan Ha\\.conda\\envs\\Cal2020\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Kil-Chan Ha\\.conda\\envs\\Cal2020\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Kil-Chan Ha\\.ipython']

### numpy의 보충 설명

* np.allclose : np.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    - 각 성분별로 absolute(`a` - `b`) <= (`atol` + `rtol` * absolute(`b`)) 이면 True
    
* ndarray.diagonal : 주어진 2차원 배열 A의 A[i,i]성분들로 이루어진 1차원 배열 반환

* np.diag : 입력이 2차원 배열이면 ndarray.diagnoal과 같은 효과, 입력이 1차원 배열이면 주어진 값을 대각성분으로 갖는 2차원 배열 반환

* np.where : np.where(조건, x, y) 성분별로 조건이 참이면 x, 거짓이면 y가 되도록 배열을 반환

* np.eye: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

    - N,M이 다를 수 있고
    - k값을 양수로 주면 주대각선 위의 대각선, 음수로 주면 주대각선 아래의 대각선에 1 
    - np.identity(n)은 np.eye(n)과 동일

In [3]:
# np.allclose : np.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
#   - 각 성분별로 absolute(`a` - `b`) <= (`atol` + `rtol` * absolute(`b`)) 이면 True

np.allclose([1e10,1e-8], [1.00001e10,1e-9])

True

In [4]:
# ndarray.diagonal : 주어진 2차원 배열 A의 A[i,i]성분들로 이루어진 1차원 배열 반환

A1 = np.array([[3,4,2],[1,2,5],[0,1,4]])
A2 = np.array([[1,2,3,4],[5,6,7,8]])
print(A1)
print()
print(A2)

[[3 4 2]
 [1 2 5]
 [0 1 4]]

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
print(A1.diagonal())
print()
print(A2.diagonal())

[3 2 4]

[1 6]


In [6]:
#np.diag : 입력이 2차원 배열이면 ndarray.diagnoal과 같은 효과, 입력이 1차원 배열이면 주어진 값을 대각성분으로 갖는 2차원 배열 반환

B = np.diag([1,2,3])
print(B)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [7]:
np.diagonal(A1)

array([3, 2, 4])

In [8]:
# np.where : np.where(조건, x, y) 성분별로 조건이 참이면 x, 거짓이면 y가 되도록 배열을 반환

upper = np.array([[True if i <=j else False for j in range(5)] for i in range(5)])

In [9]:
upper

array([[ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False, False,  True,  True],
       [False, False, False, False,  True]])

In [10]:
A = np.arange(1,26).reshape((5,5))
np.where(upper, A, np.zeros_like(A))

array([[ 1,  2,  3,  4,  5],
       [ 0,  7,  8,  9, 10],
       [ 0,  0, 13, 14, 15],
       [ 0,  0,  0, 19, 20],
       [ 0,  0,  0,  0, 25]])

In [11]:
np.where(~upper, A, np.zeros_like(A))

array([[ 0,  0,  0,  0,  0],
       [ 6,  0,  0,  0,  0],
       [11, 12,  0,  0,  0],
       [16, 17, 18,  0,  0],
       [21, 22, 23, 24,  0]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(3,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [16]:
np.eye(3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

### 모듈로부터 LUsolve 읽어들여서 사용하기

In [17]:
def myprint(A, tol=1.0e-7):
    return np.round(A.copy() / tol)* tol

In [18]:
def myLU(LU):
    n = len(LU)
    upper = np.array([[True if i <=j else False for j in range(5)] for i in range(5)])
    U = np.where(upper, LU, np.zeros_like(LU))
    L = np.where(~upper, LU, np.zeros_like(LU)) + np.eye(n)
    return L, U

In [19]:
A = np.array([[2, -2, 0, 0, 0],[-2, 5, -6, 0, 0], [0, -6, 16, 12, 0], [0, 0, 12, 39, -6], [0, 0, 0, -6, 14]])
b = np.array([1, 0, 0, 0, 0])

In [20]:
A1 = 1.0 * A.copy()
b1 = 1.0 * b.copy()

In [21]:
x = LUsolve(A1, b1)

In [22]:
myprint(x)

array([ 85.8333333,  85.3333333,  42.5      , -14.       ,  -6.       ])

In [23]:
print(np.dot(A,x))

[1.00000000e+00 2.84217094e-14 0.00000000e+00 2.84217094e-14
 0.00000000e+00]


In [24]:
myprint(np.dot(A,x))

array([1., 0., 0., 0., 0.])

In [25]:
np.allclose(np.dot(A,x),b)

True

In [26]:
LU, seq = LUdecomp(1.0*A.copy())

In [27]:
AL, AU = myLU(LU)

In [28]:
A[seq,:]

array([[ 2, -2,  0,  0,  0],
       [-2,  5, -6,  0,  0],
       [ 0,  0, 12, 39, -6],
       [ 0,  0,  0, -6, 14],
       [ 0, -6, 16, 12,  0]])

In [29]:
myprint(np.dot(AL, AU))    # PA = LU

array([[ 2., -2.,  0.,  0.,  0.],
       [-2.,  5., -6.,  0.,  0.],
       [ 0.,  0., 12., 39., -6.],
       [ 0.,  0.,  0., -6., 14.],
       [ 0., -6., 16., 12.,  0.]])

### LU 분해를 이용한 역행렬 구현

In [30]:
def matInv(a, tol=1.0e-15):
    n = len(a[0])
    aInv = np.eye(n)
    
    aa, seq = LUdecomp(1.0 * a, tol)
    
    for i in range(n):
        aInv[:, i] = LUsolve_pre(aa, aInv[:, i], seq)
    return aInv 

In [31]:
Ainv = matInv(A)

In [32]:
print(Ainv)

[[ 85.83333333  85.33333333  42.5        -14.          -6.        ]
 [ 85.33333333  85.33333333  42.5        -14.          -6.        ]
 [ 42.5         42.5         21.25        -7.          -3.        ]
 [-14.         -14.          -7.           2.33333333   1.        ]
 [ -6.          -6.          -3.           1.           0.5       ]]


In [33]:
print(np.allclose(np.dot(A,Ainv), np.eye(5)))

True


In [34]:
myprint(np.dot(A,Ainv))

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [-0., -0.,  1., -0., -0.],
       [ 0.,  0.,  0.,  1., -0.],
       [-0., -0., -0.,  0.,  1.]])

In [35]:
def vandermonde(v):
    """a = vandermonde(v)
       입력 벡터 v에 대해 a[i,j]=v[i]**(n-j-1)인 행렬 a를 반환하는 함수"""
    n = len(v)
    a = np.zeros((n,n))
    for j in range(n):
        a[:,j] = v**(n-j-1)
    return a

In [36]:
AA = vandermonde(np.array([1,3,5,7,9]))

In [37]:
myprint(AA)

array([[1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00],
       [8.100e+01, 2.700e+01, 9.000e+00, 3.000e+00, 1.000e+00],
       [6.250e+02, 1.250e+02, 2.500e+01, 5.000e+00, 1.000e+00],
       [2.401e+03, 3.430e+02, 4.900e+01, 7.000e+00, 1.000e+00],
       [6.561e+03, 7.290e+02, 8.100e+01, 9.000e+00, 1.000e+00]])

In [38]:
AAinv = matInv(AA*1.0)

In [39]:
myprint(np.dot(AA, AAinv))

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -0.,  0., -0.],
       [-0., -0.,  1.,  0.,  0.],
       [ 0., -0., -0.,  1.,  0.],
       [ 0., -0., -0.,  0.,  1.]])

### LU 분해를 이용한 행렬식 계산

In [40]:
np.prod(np.array([1,3,5]))

15

In [41]:
def sgn(perm):
    n = len(perm)
    ctr = 0
    for i in range(n):
        ctr += (perm[:list(perm).index(i)]>i).sum()
    return -1 if (ctr % 2) else 1  

In [42]:
def matDet(a):
    aa, seq = LUdecomp(1.0 *a)
    return np.prod(np.diag(aa)) * sgn(seq)

In [43]:
print(A)

[[ 2 -2  0  0  0]
 [-2  5 -6  0  0]
 [ 0 -6 16 12  0]
 [ 0  0 12 39 -6]
 [ 0  0  0 -6 14]]


In [44]:
matDet(A)

143.9999999999999

# 과제물 

### (1) 다음 조건을 만족하는 함수 LUdecompSym을 작성하시오. (15점)

* $n\times n$ 행렬 $A$가 대칭행렬일 때, $A = LDL^{\rm T}$와 같이 분해하여 하삼각행렬 $L$과 대각행렬 $D$를 반환하는 함수 LUdecompSym(A)를 작성하시오.

* 단, 함수를 실행시킨 후 입력 $A$는 변하지 않도록 작성해야 합니다. 

### (2) 다음 조건을 만족하는 Choleski 함수를 작성하시오. (15점)

* $A$가 양의 정부호 행렬일 때, $A = LL^{\rm T}$를 만족하는 하삼각행렬 $L$을 반환하는 함수 Choleski(A)를 작성하시오. 

* 단, 함수를 실행시킨 후 입력 $A$는 변하지 않도록 작성해야 합니다. 

In [45]:
?np.linalg

In [46]:
myprint(np.linalg.inv(A))

array([[ 85.8333333,  85.3333333,  42.5      , -14.       ,  -6.       ],
       [ 85.3333333,  85.3333333,  42.5      , -14.       ,  -6.       ],
       [ 42.5      ,  42.5      ,  21.25     ,  -7.       ,  -3.       ],
       [-14.       , -14.       ,  -7.       ,   2.3333333,   1.       ],
       [ -6.       ,  -6.       ,  -3.       ,   1.       ,   0.5      ]])